collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/stream/:slugified_categories/:year:month-:title"
      layout: "post"

  - scope:
      path: "assets/tracks"
    values:
      type: gpx
  
  - scope:
      path: ""
      type: tracks
    values:
      layout: track_page
      permalink: /:category/:basename.html

exclude:
  - "*readme.md"