permalink: "/:categories/:title"

collections:
  people:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
      
exclude:
  - "*readme.md"